apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    tier: frontend

spec:
  template:
    metadata:
      name: nginxserver
      labels:
        app: myapp
    spec:
      containers:
        - name: webserver
          image: nginx
  
  replicas: 1
  selector:
    matchLabels:
      app: myapp
